export default [
    {
      name: "Veggieburgers",
      datetime: "Mcdonald's",
      Image: require("../../assets/Burger01.jpg"),
      Image1: require("../../assets/star.jpg"),
      text1:"4.6",
      clock:require("../../assets/clock.jpg"),
      time:"30 min",
      save:require("../../assets/save.jpg"),
      text2:"$55",
    },
    {
      name: "Cheeseburger",
      datetime: "Mcdonald's",
      Image: require("../../assets/Burger02.jpg"),
      Image1: require("../../assets/star.jpg"),
      text1:"4.5",
      clock:require("../../assets/clock.jpg"),
      time:"40 min",
      save:require("../../assets/save.jpg"),
      text2:"$53",
    },
    {
      name: "Veggieburgers",
      datetime: "Mcdonald's",
      Image: require("../../assets/Burger01.jpg"),
      Image1: require("../../assets/star.jpg"),
      text1:"4.6",
      clock:require("../../assets/clock.jpg"),
      time:"30 min",
      save:require("../../assets/save.jpg"),
      text2:"$55",
    },
    {
      name: "Cheeseburger",
      datetime: "Mcdonald's",
      Image: require("../../assets/Burger02.jpg"),
      Image1: require("../../assets/star.jpg"),
      text1:"4.5",
      clock:require("../../assets/clock.jpg"),
      time:"40 min",
      save:require("../../assets/save.jpg"),
      text2:"$53",
    },
    {
      name: "Veggieburgers",
      datetime: "Mcdonald's",
      Image: require("../../assets/Burger01.jpg"),
      Image1: require("../../assets/star.jpg"),
      text1:"4.6",
      clock:require("../../assets/clock.jpg"),
      time:"30 min",
      save:require("../../assets/save.jpg"),
      text2:"$55",
    },
    {
      name: "Cheeseburger",
      datetime: "Mcdonald's",
      Image: require("../../assets/Burger02.jpg"),
      Image1: require("../../assets/star.jpg"),
      text1:"4.5",
      clock:require("../../assets/clock.jpg"),
      time:"40 min",
      save:require("../../assets/save.jpg"),
      text2:"$53",
    }, 
    {
      name: "Veggieburgers",
      datetime: "Mcdonald's",
      Image: require("../../assets/Burger01.jpg"),
      Image1: require("../../assets/star.jpg"),
      text1:"4.6",
      clock:require("../../assets/clock.jpg"),
      time:"30 min",
      save:require("../../assets/save.jpg"),
      text2:"$55",
    },
    {
      name: "Cheeseburger",
      datetime: "Mcdonald's",
      Image: require("../../assets/Burger02.jpg"),
      Image1: require("../../assets/star.jpg"),
      text1:"4.5",
      clock:require("../../assets/clock.jpg"),
      time:"40 min",
      save:require("../../assets/save.jpg"),
      text2:"$53",
    },
    
  ];
  